services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build: .
    image: 361093688129.dkr.ecr.us-west-2.amazonaws.com/django_docker_aws_1
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py makemigrations mysite &&
             python manage.py migrate mysite &&
            {  
              export DJANGO_SUPERUSER_EMAIL=test@test.com
              export DJANGO_SUPERUSER_PASSWORD=test1 &&
              python manage.py createsuperuser --noinput --username hanna &&
              python manage.py runserver 0.0.0.0:8000
            } || 
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy


  # will need to add htis back in if I start it on a new computer or delte  the db
  #export DJANGO_SUPERUSER_EMAIL=test@test.com
  #            export DJANGO_SUPERUSER_PASSWORD=test1 &&
  #            python manage.py createsuperuser --noinput --username hanna &&